[package]
name = "extract-ikconfig-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ikconfig"
path = "src/main.rs"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = "symbols"

[dependencies]
clap = "4.0.19"
flate2 = "1.0.24"
grep-matcher = "0.1.5"
grep-regex = "0.1.10"
grep-searcher = "0.1.10"
regex = "1.7.0"

[dev-dependencies]
assert_cmd = "2.0.6"
chrono = "0.4.22"
