name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup prerequisites
        shell: bash
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install lzop

      - name: Setup prerequisites
        shell: bash
        if: matrix.os == 'macOS-latest'
        run: |
          brew install lzop

      - name : Toolchain info
        run: |
          cargo --version --verbose
          rustc --version --verbose

      - name: Run cargo build
        run: |
          cargo build --release

      - name: Run cargo clippy
        run: |
          cargo clippy
        env:
          CI: true

      - name: Run cargo test
        run: |
          cargo test --release --test integration  -- --show-output

